### ISSUE TITLE
Can't create new profile

### ISSUE THREAD

**Issue by Dont-Know-Nothing** [Ryochan7/SteamControllerTest#10]
Hi. First thanks for this, I just started to use it and I really like the possibility of using my SC without Steam. My coding skills are almost 0 but I'll try to learn C# just for this.

The issue: Starting the app doesn't show any profile, trying to create a new one, when browsing for path, always ends in "Cannot move to a different directory" I fixed it copying example_files folder profiles to %AppData%\Roaming\SCTest\Profiles\SteamController.

I guess this repo is just for personal testing? so, sorry if I bother you.

**Comment by Ryochan7** [comment]
Keeping profiles isolated a device specific profiles folder was a deliberate design decision. Not sure how to keep a file dialog isolated to one folder so that check is put in place after using the file dialog. So it is working as intended but it could be more straight forward.

This repo is mostly for testing a possible newer mapper system with the Steam Controller. The DS4MapperTest repo is the main place for development of the mapper system lately but that project does not have Steam Controller support; it currently supports the DS4, DualSense, and Switch Pro controllers. Neither repo is at the point where I would take either out of beta status; that might not ever happen TBH. Been using the programs for playing games that would not have been feasible using DS4Windows.

**Comment by Dont-Know-Nothing** [comment]
Thanks again I've already being using this for old Directinput games (SH3) and works better than Steam. I've used DS4Windows for a long time with a DualSense (thanks for that) but now I have a SC and I being looking for a Windows solution without much luck until now. 

Are you using VS 2022 or 2019 with some workaround for .NET 6.0 or anything else? I really want to give it a try.
And again, sorry won't bother you any longer.

**Comment by Ryochan7** [comment]
I use VS 2022 for this project and almost every other C# project I work on. Still have VS 2019 installed for some ViGEm projects that require it.
