### ISSUE TITLE
Mapping Touchpad as TouchStickTranslateAction breaks  Gyro mapping as GyroMouseJoystick Action

### ISSUE THREAD

**Issue by Dont-Know-Nothing** [Ryochan7/SteamControllerTest#22]
Hi! I know you aren't doing much on this repo but.

I've tried to map the right Touchpad as joystick because Mouse-LikeJoystick  is kind of acting strange but, the moment I do that, gyro doesn't work anymore.

When I try to edit the "Output Stick" field, it ends up always as Unbound. Then.. if I manually edit the .json file and put "OutputStick": "RS", the gyro starts working.  but again... if I map the right touchpad as Joystick one more time, gyro doesn't work.
Don't know if I make any sense.. I've tried to debug this but I never gonna get this WPF + MVVM stuff  I'm too old for this shit :)

Thanks again!

**Comment by Ryochan7** [comment]
Confirmed. Not sure when that broke as I have used GyroMouseJoystick for profiles fine in the past. Probably should also set Right Stick as the default option for Output Stick rather than Unbound. There are not many times when Left Stick would be used as an option but there are some times when it would come in handy; Resident Evil 4 (2005) was the main time I bound Gyro to Left Stick for aiming.

One extra thing to be mindful of is that the default Trigger option for the Gyro is Always On. With that option enabled, the Gyro will always control the value of the output stick. I think I had tried to change that with the DS4 version of this mapper so the output value would not get changed to zero under certain circumstances. I never got around to committing anything in either repo though.

I am likely older than you are. It took me a while to understand MVVM and adapt it to my coding style; online tutorials did not really help that much as it seemed mostly pointless for the use cases presented. Now I use that pattern outside of .NET projects as well. WPF was much easier to get started using.

**Comment by Ryochan7** [comment]
https://github.com/Ryochan7/SteamControllerTest/commit/cf51eaf2811b4a825979cb1614795573b7b757ae
https://github.com/Ryochan7/SteamControllerTest/commit/91b698074e943e3c0cf5907e136355788791fb6b

Got it resolved. Missed a small edit I made so needed a second commit. The output stick value was not being set at all.

**Comment by Dont-Know-Nothing** [comment]
I must be doing something wrong.. the issue persist in my end. I've synced the repo and done all over again in VS but still there.
same as before, with the right touchpad unbounded the gyro works (always on and with right trigger as ratchet). The moment I map the right touchpad to Mouse-like Joystick gyro stops working. (works fine as mouse though).

I'm 45, and my little coding skills are on VB6 from 15 years ago. I watched dozens of MVVM tutorials and the only thing I get is frustration :) but hey... I'm gonna keep trying!
